# Generated by Django 2.1.3 on 2018-12-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
