# Generated by Django 2.1.3 on 2018-12-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0002_auto_20181209_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apt_name', models.CharField(max_length=50)),
                ('Flat_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='Apt_name',
            field=models.CharField(default='ABC', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Flat_no',
            field=models.CharField(default='ABC', max_length=100),
        ),
    ]
