# Generated by Django 2.1.3 on 2018-12-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0003_auto_20181223_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='Flat_no',
        ),
        migrations.AddField(
            model_name='apartment',
            name='Apt_address',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='Apt_district',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='Apt_phoneNo',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='Apt_pincode',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='Apt_state',
            field=models.CharField(default='ABC', max_length=100),
        ),
    ]
