# Generated by Django 2.1.3 on 2018-12-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0005_auto_20181224_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpinghand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Helper1', models.CharField(default='', max_length=100)),
                ('Helper2', models.CharField(default='', max_length=100)),
                ('Helper3', models.CharField(default='', max_length=100)),
                ('Helper4', models.CharField(default='', max_length=100)),
                ('Helper5', models.CharField(default='', max_length=100)),
                ('Helper6', models.CharField(default='', max_length=100)),
                ('Helper1_role', models.CharField(default='', max_length=100)),
                ('Helper2_role', models.CharField(default='', max_length=100)),
                ('Helper3_role', models.CharField(default='', max_length=100)),
                ('Helper4_role', models.CharField(default='', max_length=100)),
                ('Helper5_role', models.CharField(default='', max_length=100)),
                ('Helper6_role', models.CharField(default='', max_length=100)),
                ('Helper1_contact', models.CharField(default='', max_length=100)),
                ('Helper2_contact', models.CharField(default='', max_length=100)),
                ('Helper3_contact', models.CharField(default='', max_length=100)),
                ('Helper4_contact', models.CharField(default='', max_length=100)),
                ('Helper5_contact', models.CharField(default='', max_length=100)),
                ('Helper6_contact', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
