# Generated by Django 2.1.3 on 2018-12-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0006_helpinghand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='Apt_phoneNo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper1_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper1_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper2_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper2_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper3_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper3_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper4_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper4_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper5_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper5_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper6_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Helper6_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
