# Generated by Django 2.1.3 on 2018-12-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0007_auto_20181231_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpinghand',
            name='Apt_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Apt_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
