# Generated by Django 2.1.3 on 2019-01-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0008_auto_20181231_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartmentname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apt_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Apt_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weloft.Apartmentname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Apt_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weloft.Apartmentname'),
        ),
        migrations.AlterField(
            model_name='helpinghand',
            name='Apt_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weloft.Apartmentname'),
        ),
    ]
