# Generated by Django 2.1.4 on 2019-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weloft', '0009_auto_20190104_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apt_name', models.CharField(default='', max_length=50)),
                ('Facility1', models.CharField(blank=True, default='', max_length=100)),
                ('Max_Occupancy1', models.CharField(blank=True, default='', max_length=100)),
                ('Facility2', models.CharField(blank=True, default='', max_length=100)),
                ('Max_Occupancy2', models.CharField(blank=True, default='', max_length=100)),
                ('Facility3', models.CharField(blank=True, default='', max_length=100)),
                ('Max_Occupancy3', models.CharField(blank=True, default='', max_length=100)),
                ('Facility4', models.CharField(blank=True, default='', max_length=100)),
                ('Max_Occupancy4', models.CharField(blank=True, default='', max_length=100)),
                ('Facility5', models.CharField(blank=True, default='', max_length=100)),
                ('Max_Occupancy5', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
